<p>
    <?php if ($identity === null): ?>

    <a href="<?php echo $this->url('user', array('action' => 'login')); ?>">Login</a><br/>

<p>
    Not logged in.
</p>

<?php else: ?>


<a href="<?php echo $this->url('analytics', array('action' => 'index')); ?>">Analysis & Insights</a>
<br/>
<br/>
<a href="<?php echo $this->url('user', array('action' => 'logout')); ?>">Logout</a><br/>

<p>
    <br/>
    Logged in as <strong><?php echo $identity ?></strong>.
</p>
<?php endif; ?>
</p>
